export {
  HomeNavIcon,
  IdentitiesNavIcon,
  PoliciesNavIcon,
  RulesNavIcon,
  ScansNavIcon,
  ApplicationsAccessReviewNavIcon,
  AppsAndSecuredItemsNavIcon,
  InfrastructureNavIcon,
  ThreatDetectionAndResponse,
  SessionMonitoring,
  SecurityInsightsNavIcon,
  SystemActivitiesNavIcon,
  ReportsNavIcon,
  InventoryNavIcon,
  AccessRequestsNavIcon,
  AccessCertificationNavIcon,
  HealthDiagnosticsNavIcon,
  DeploymentNavIcon,
  LicenseUsageNavIcon,
} from './navigationIcons';
